### PR TITLE
No more AggregateRoot in RailsEventStore, extracted to separete gem

### PR DESCRIPTION
**Pull request by mpraglowski**
Moved to separate gem https://github.com/arkency/aggregate_root

### CODE REVIEW

**Comment by mpraglowski** [comment]
@gottfrois what about this PR ?

**Comment by gottfrois** [comment]
Sounds pretty good.

**Comment by gottfrois** [comment]
Might want to update the readme

**Comment by mpraglowski** [comment]
@gottfrois done

**Pull request merged**
