### PR TITLE
Allows to set the event repository used.

### PR DESCRIPTION
**Pull request by gottfrois**
By default it will use the active_record event repository. If you want to
use another event repository without loading unecessary active_record
dependency, you'll need to do:

```
gem 'rails_event_store', require: false
gem 'rails_event_store_mongoid'
```

Then require manually `rails_event_store` gem dy doing:

```
require 'rails_event_store/all'
```

This will prevent loading `rails_event_store_active_record` gem by default.

Finally, specify the event repository adapter with:

```
RailsEventStore::Repository.adapter = :mongoid
```

It will look for a class named `RailsEventStoreMongoid::EventRepository`

### Help Needed to kill the mutants

@mpraglowski I was not able to kill the last mutant. Can you give me a hand?

```
RailsEventStore::Repository.adapter=:/Users/gottfrois/Code/rails_event_store/lib/rails_event_store/repository.rb:7
- rspec:16:./spec/repository_spec.rb:19/RailsEventStore::Repository.adapter= when passing nil
- rspec:17:./spec/repository_spec.rb:31/RailsEventStore::Repository.adapter= when passing a string which module exists
- rspec:18:./spec/repository_spec.rb:43/RailsEventStore::Repository.adapter= when passing a string when passing a symbol which module exists
- rspec:19:./spec/repository_spec.rb:62/RailsEventStore::Repository.adapter= when passing an object
evil:RailsEventStore::Repository.adapter=:/Users/gottfrois/Code/rails_event_store/lib/rails_event_store/repository.rb:7:54d08
@@ -1,9 +1,9 @@
 def self.adapter=(adapter)
   case adapter
   when String, Symbol
     @@adapter = "#{"::RailsEventStore"}#{adapter.to_s.classify}#{"::EventRepository"}".constantize.new
   else
-    @@adapter = adapter
+    @@adapter = nil
   end
 end
```

### CODE REVIEW

**Comment by mpraglowski** [comment]
@gottfrois killed the mutants by removing magic ;)

instead of:

```
require 'rails_event_store/all'
RailsEventStore::Repository.adapter = :mongoid
```

you now need to:

```
require 'rails_event_store/all'
RailsEventStore.event_repository = RailsEventStoreMongoid::EventRepository.new
```

I will update documentation soon.

**Comment by mpraglowski** [comment]
here updated docs: http://railseventstore.arkency.com/docs/repository.html

**Comment by gottfrois** [comment]
@mpraglowski any chance to see the changes in a release gem version

**Comment by mpraglowski** [comment]
@gottfrois done

**Pull request merged**
